# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dog
  pod 'Masonry'
#  pod 'SDWebImage'
#  pod 'YYModel'
#  pod 'AFNetworking'
  pod 'BmobSDK'
  pod 'SSZipArchive'
  pod 'JPush'
  
end
